### ISSUE TITLE
How to confiure this plugin into prestosql-316?

### ISSUE THREAD

**Issue by prashant-jain** [marcelopaesrech/presto-oracle#11]
Hi @marcelopaesrech 
I have setup [prestosql-316](https://github.com/prestosql/presto) in my hadoop cluster now I need your plugin to query on oracle.
I have done all the steps that you have mentioned in readme file. But I'm unable to start the presto server. 

**getting error:** 
2019-07-26T17:54:00.794+0700    INFO    main    io.prestosql.server.PluginManager    -- Loading plugin /bi20/presto/presto-server-316/plugin/oracle --
2019-07-26T17:54:00.798+0700    ERROR    main    io.prestosql.server.PrestoServer    No service providers of type io.prestosql.spi.Plugin
java.lang.IllegalStateException: No service providers of type io.prestosql.spi.Plugin
    at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
    at io.prestosql.server.PluginManager.loadPlugin(PluginManager.java:158)
    at io.prestosql.server.PluginManager.loadPlugin(PluginManager.java:149)
    at io.prestosql.server.PluginManager.loadPlugins(PluginManager.java:130)
    at io.prestosql.server.PrestoServer.run(PrestoServer.java:125)
    at io.prestosql.server.PrestoServer.main(PrestoServer.java:70)
2019-07-26T17:54:00.799+0700    INFO    Thread-99    io.airlift.bootstrap.LifeCycleManager    Life cycle stopping...

**Comment by tooptoop4** [comment]
Y u not use fb 225?
