### ISSUE TITLE
Presto 0.190 and 0.189 have breaking changes for the oracle plugin.

### ISSUE THREAD

**Issue by brokenjacobs** [marcelopaesrech/presto-oracle#6]
Presto 0.190 deprecates the recordsinkprovider leading to this:

Dec 07 21:35:15 den-devpresto-1.ci.neoninternal.org presto[112542]: java.lang.NoClassDefFoundError: com/facebook/presto/spi/connector/ConnectorRecordSinkProvider

0.189 adds support for decimal types

I'd also like to bring a PR in that imports VIEWS and sets the fetchsize higher.

**Comment by sajjoseph** [comment]
Can you post the full stack trace? 
I use the oracle connector in 0.189 version and haven't come across issues. It could be that I haven't used queries that could trigger the failure you observed.

Thanks

**Comment by jgtree420** [comment]
I am also hitting this issue with 0.193 trying to use the Oracle plugin
```2018-02-09T22:55:17.909Z	ERROR	main	com.facebook.presto.server.PrestoServer	com/facebook/presto/spi/connector/ConnectorRecordSinkProvider
java.lang.NoClassDefFoundError: com/facebook/presto/spi/connector/ConnectorRecordSinkProvider
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.facebook.presto.server.PluginClassLoader.loadClass(PluginClassLoader.java:80)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.facebook.presto.plugin.jdbc.JdbcModule.configure(JdbcModule.java:40)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at io.airlift.configuration.ConfigurationFactory.registerConfigurationClasses(ConfigurationFactory.java:164)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:200)
	at com.facebook.presto.plugin.jdbc.JdbcConnectorFactory.create(JdbcConnectorFactory.java:71)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:303)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:191)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:183)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:169)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:118)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:66)
Caused by: java.lang.ClassNotFoundException: com.facebook.presto.spi.connector.ConnectorRecordSinkProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.facebook.presto.server.PluginClassLoader.loadClass(PluginClassLoader.java:76)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more```

**Comment by sajjoseph** [comment]
I too saw the error when I didn't clean the folder and there were leftover jars.
You have to remove the contents of /usr/lib/presto/lib/plugin/oracle folder - and then redeploy the necessary jars for this connector into the said folder. It fixed the problem for me. Let me know if you have any questions.

**Comment by omarpando** [comment]
Hello @sajjoseph, in the README file the author suggest 
```
cd $PRESTODB_HOME
cp -r plugin/mysql plugin/oracle
rm plugin/oracle/mysql-connector*
rm plugin/oracle/presto-mysql*

```
are you saying we should not copy the contents of mysql to 'reuse' it ?
