### ISSUE TITLE
throws error while running presto-server

### ISSUE THREAD

**Issue by Gaurang033** [marcelopaesrech/presto-oracle#9]
hi I was not able to download the **ojdbc6.jar** through maven so i modifed the maven and build the jar. However I am getting following error while running the server. 
**modified pom.xml**
```
      <groupId>ojdbc6</groupId>
        <artifactId>ojdbc6</artifactId>
        <version>1.0</version>
        <scope>system</scope>
        <systemPath>./ojdbc6.jar</systemPath>
        </dependency>

```

**Error:**
```
2) Error injecting constructor, java.lang.NoClassDefFoundError: oracle/jdbc/OracleDriver
  at com.facebook.presto.plugin.oracle.OracleClient.<init>(OracleClient.java:61)
  while locating com.facebook.presto.plugin.oracle.OracleClient
  at com.facebook.presto.plugin.oracle.OracleClientModule.configure(OracleClientModule.java:34)
  while locating com.facebook.presto.plugin.jdbc.JdbcClient
    for the 1st parameter of com.facebook.presto.plugin.jdbc.JdbcMetadataFactory.<init>(JdbcMetadataFactory.java:27)
  at com.facebook.presto.plugin.jdbc.JdbcModule.configure(JdbcModule.java:37)
  while locating com.facebook.presto.plugin.jdbc.JdbcMetadataFactory
Caused by: java.lang.NoClassDefFoundError: oracle/jdbc/OracleDriver
	at com.facebook.presto.plugin.oracle.OracleClient.<init>(OracleClient.java:61)
	at com.facebook.presto.plugin.oracle.OracleClient$$FastClassByGuice$$f65e92c6.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:241)
	at com.facebook.presto.plugin.jdbc.JdbcConnectorFactory.create(JdbcConnectorFactory.java:71)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:319)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:195)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:187)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:173)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:119)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
```

**Comment by Gaurang033** [comment]
after putting the **ojdbc6.jar** in plugin\oracle folder, above error has resolved however getting another stack-trace. 
```
2018-08-09T10:59:29.214-0400	INFO	main	com.facebook.presto.metadata.StaticCatalogStore	-- Loading catalog etc/catalog/oracle.properties --
2018-08-09T10:59:29.445-0400	INFO	main	Bootstrap	PROPERTY             DEFAULT     RUNTIME                                       DESCRIPTION
2018-08-09T10:59:29.445-0400	INFO	main	Bootstrap	connection-password  [REDACTED]  [REDACTED]
2018-08-09T10:59:29.445-0400	INFO	main	Bootstrap	connection-url       null        jdbc:oracle:thin://myhost:25781/mydb
2018-08-09T10:59:29.445-0400	INFO	main	Bootstrap	connection-user      null        myuser
2018-08-09T10:59:29.445-0400	INFO	main	Bootstrap	allow-drop-table     false       false                                         Allow connector to drop tables
2018-08-09T10:59:29.445-0400	INFO	main	Bootstrap	oracle.password      null        null
2018-08-09T10:59:29.445-0400	INFO	main	Bootstrap	oracle.user          null        null
2018-08-09T10:59:29.613-0400	ERROR	main	com.facebook.presto.server.PrestoServer	Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: com.facebook.presto.plugin.jdbc.BaseJdbcClient.<init>(Lcom/facebook/presto/plugin/jdbc/JdbcConnectorId;Lcom/facebook/presto/plugin/jdbc/BaseJdbcConfig;Ljava/lang/String;Ljava/sql/Driver;)V
  at com.facebook.presto.plugin.oracle.OracleClient.<init>(OracleClient.java:61)
  while locating com.facebook.presto.plugin.oracle.OracleClient
  at com.facebook.presto.plugin.oracle.OracleClientModule.configure(OracleClientModule.java:34)
  while locating com.facebook.presto.plugin.jdbc.JdbcClient
Caused by: java.lang.NoSuchMethodError: com.facebook.presto.plugin.jdbc.BaseJdbcClient.<init>(Lcom/facebook/presto/plugin/jdbc/JdbcConnectorId;Lcom/facebook/presto/plugin/jdbc/BaseJdbcConfig;Ljava/lang/String;Ljava/sql/Driver;)V
	at com.facebook.presto.plugin.oracle.OracleClient.<init>(OracleClient.java:61)
	at com.facebook.presto.plugin.oracle.OracleClient$$FastClassByGuice$$f65e92c6.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:241)
	at com.facebook.presto.plugin.jdbc.JdbcConnectorFactory.create(JdbcConnectorFactory.java:71)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:319)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:195)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:187)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:173)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:119)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
```

**Comment by geomartinez** [comment]
I'm seeing this second error too. @Gaurang033 @marcelopaesrech Did you ever find a fix for this

**Comment by xbyang18** [comment]
@Gaurang033 @geomartinez 
hi,I'm seeing it error too,and it so like that the version incompatibility,Dis you done it ?

**Comment by PreethiS** [comment]
hi did you find a fix for this?

**Comment by sajjoseph** [comment]
https://github.com/prestodb/presto/pull/11540 - try this one.
https://github.com/prestodb/presto/blob/a89aa46440b6eca9a96f2aa3b12cde8f33a8c40b/presto-oracle/README.md has details on how to use it.
